/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTransportRouteImport } from './routes/_app.transport'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppTeachersRouteImport } from './routes/_app.teachers'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppPortalRouteImport } from './routes/_app.portal'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppParentsRouteImport } from './routes/_app.parents'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppHostelRouteImport } from './routes/_app.hostel'
import { Route as AppFeesRouteImport } from './routes/_app.fees'
import { Route as AppExaminationsRouteImport } from './routes/_app.examinations'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAssignmentsRouteImport } from './routes/_app.assignments'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAdmissionsRouteImport } from './routes/_app.admissions'
import { Route as AppStudentsIdRouteImport } from './routes/_app.students.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppParentsRoute = AppParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHostelRoute = AppHostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppExaminationsRoute = AppExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admissions': typeof AppAdmissionsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assignments': typeof AppAssignmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/classes': typeof AppClassesRoute
  '/examinations': typeof AppExaminationsRoute
  '/fees': typeof AppFeesRoute
  '/hostel': typeof AppHostelRoute
  '/library': typeof AppLibraryRoute
  '/messages': typeof AppMessagesRoute
  '/parents': typeof AppParentsRoute
  '/payroll': typeof AppPayrollRoute
  '/portal': typeof AppPortalRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/teachers': typeof AppTeachersRoute
  '/timetable': typeof AppTimetableRoute
  '/transport': typeof AppTransportRoute
  '/students/$id': typeof AppStudentsIdRoute
}
export interface FileRoutesByTo {
  '/admissions': typeof AppAdmissionsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assignments': typeof AppAssignmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/classes': typeof AppClassesRoute
  '/examinations': typeof AppExaminationsRoute
  '/fees': typeof AppFeesRoute
  '/hostel': typeof AppHostelRoute
  '/library': typeof AppLibraryRoute
  '/messages': typeof AppMessagesRoute
  '/parents': typeof AppParentsRoute
  '/payroll': typeof AppPayrollRoute
  '/portal': typeof AppPortalRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/teachers': typeof AppTeachersRoute
  '/timetable': typeof AppTimetableRoute
  '/transport': typeof AppTransportRoute
  '/': typeof AppIndexRoute
  '/students/$id': typeof AppStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admissions': typeof AppAdmissionsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/assignments': typeof AppAssignmentsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/examinations': typeof AppExaminationsRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/hostel': typeof AppHostelRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/parents': typeof AppParentsRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/transport': typeof AppTransportRoute
  '/_app/': typeof AppIndexRoute
  '/_app/students/$id': typeof AppStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/analytics'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/calendar'
    | '/classes'
    | '/examinations'
    | '/fees'
    | '/hostel'
    | '/library'
    | '/messages'
    | '/parents'
    | '/payroll'
    | '/portal'
    | '/roles'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admissions'
    | '/analytics'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/calendar'
    | '/classes'
    | '/examinations'
    | '/fees'
    | '/hostel'
    | '/library'
    | '/messages'
    | '/parents'
    | '/payroll'
    | '/portal'
    | '/roles'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/'
    | '/students/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admissions'
    | '/_app/analytics'
    | '/_app/announcements'
    | '/_app/assignments'
    | '/_app/attendance'
    | '/_app/calendar'
    | '/_app/classes'
    | '/_app/examinations'
    | '/_app/fees'
    | '/_app/hostel'
    | '/_app/library'
    | '/_app/messages'
    | '/_app/parents'
    | '/_app/payroll'
    | '/_app/portal'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/teachers'
    | '/_app/timetable'
    | '/_app/transport'
    | '/_app/'
    | '/_app/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transport': {
      id: '/_app/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parents': {
      id: '/_app/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AppParentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hostel': {
      id: '/_app/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof AppHostelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/examinations': {
      id: '/_app/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof AppExaminationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admissions': {
      id: '/_app/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$id': {
      id: '/_app/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsIdRoute: typeof AppStudentsIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsIdRoute: AppStudentsIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppAdmissionsRoute: typeof AppAdmissionsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClassesRoute: typeof AppClassesRoute
  AppExaminationsRoute: typeof AppExaminationsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppHostelRoute: typeof AppHostelRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppParentsRoute: typeof AppParentsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPortalRoute: typeof AppPortalRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppTeachersRoute: typeof AppTeachersRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppTransportRoute: typeof AppTransportRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdmissionsRoute: AppAdmissionsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClassesRoute: AppClassesRoute,
  AppExaminationsRoute: AppExaminationsRoute,
  AppFeesRoute: AppFeesRoute,
  AppHostelRoute: AppHostelRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppParentsRoute: AppParentsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPortalRoute: AppPortalRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppTeachersRoute: AppTeachersRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppTransportRoute: AppTransportRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
